### ISSUE TITLE
Translate Event Handling

### ISSUE THREAD

**Issue by amiruddinid** [adityapurwa/id.vuejs.org#22]
or other pages you assign to me, i will be glad to help

**Comment by adityapurwa** [comment]
Hi, thank you for having an interest in the translation project! Feel free to choose any page that you wanted to translate. I think you can take the event handling for now, and you can create another issue for translating the list rendering page. I will update the issue title to match this. Thank you!

Good luck!

**Comment by didikz** [comment]
Hi @amiruddinid any update for this translation progress?

**Comment by amiruddinid** [comment]
@didikz got 50%, will push tonight

**Comment by adityapurwa** [comment]
Hi @amiruddinid , just wanted to check - any updates on the translation?

**Comment by dhonx** [comment]
Hi Guys... i just want to join !!!

**Comment by didikz** [comment]
Hi @donnisnoni95 please follow contribution guideline here https://github.com/adityapurwa/id.vuejs.org :)

**Comment by adityapurwa** [comment]
As there are no updates on this, I will close this.
